Controllers/AccountingController.cs
using Microsoft.AspNetCore.Mvc;
using oa.Services;
using oa.Models;
using Microsoft.AspNetCore.Authorization;
using Newtonsoft.Json;
using Microsoft.AspNetCore.Identity.UI.Services;
using oa.Areas.Identity.Data;
using Microsoft.AspNetCore.Identity;
using System.Security.Claims;
using Microsoft.AspNetCore.Mvc.Rendering;

using Microsoft.AspNetCore.Mvc.ViewFeatures;
using iText.Html2pdf;
using iText.Kernel.Pdf;
using System.IO;
using Microsoft.AspNetCore.Mvc.ModelBinding;
using Microsoft.AspNetCore.Mvc.ViewEngines;
using System.Security.Principal;

namespace OnAccount.Controllers
{
    [BindProperties(SupportsGet = true)]
    public class AccountingController : Controller
    {
        private readonly DbConnectorService _dbConnectorService;
        private readonly UserService _userService;
        List<AccountsModel> currentAccounts;
        AccountsModel accountModel;
        private readonly IEmailSender _emailSender;
        public DateTime today = DateTime.Today;
        public string? todayStr = "";
        private readonly UserManager<AppUser> _userManager;
        private readonly ICompositeViewEngine _viewEngine;
        private readonly ITempDataProvider _tempDataProvider;

        public AccountingController(DbConnectorService connectorService,
            UserService userService, IEmailSender emailSender, UserManager<AppUser> userManager, ICompositeViewEngine viewEngine, ITempDataProvider tempDataProvider)
        {
            _dbConnectorService = connectorService;
            _userService = userService;
            currentAccounts = _dbConnectorService.GetChartOfAccounts().OrderBy(a => a.number).ToList();
            accountModel = new AccountsModel();
            this._emailSender = emailSender;
            todayStr = today.ToString("MM-dd-yyyy");
            _userManager = userManager;
            _viewEngine = viewEngine;
            _tempDataProvider = tempDataProvider;
        }

        //All users can view the accounting home landing page
        [Authorize(Roles = "Administrator,Manager,Accountant")]
        public IActionResult Index()
        {
            //leaving this as example on obtaining users details from identity claims.
            var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            AppUserModel userDetails = _dbConnectorService.GetUserDetailsById(userId);

            ChartingDataService chartingService = new ChartingDataService();
            DashboardBundleModel dashboardBundleModel;
            CurrentRaitoModel currentRaitoModel;
            ReturnOnAssetsModel returnOnAssetsModel;
            ReturnOnEquityModel returnOnEquityModel;
            QuickRatioModel quickRatioModel;
            currentRaitoModel = new CurrentRaitoModel();
            currentRaitoModel.current_assets_balance = chartingService.GetAccountTypeTotalBalance("Asset", "Short");
            currentRaitoModel.current_liabilities_balance = chartingService.GetAccountTypeTotalBalance("Liability", "Short");
            returnOnAssetsModel = new ReturnOnAssetsModel();
            returnOnAssetsModel.revenues_balance = chartingService.GetAccountTypeTotalBalance("Revenue");
            returnOnAssetsModel.expenses_balance = chartingService.GetAccountTypeTotalBalance("Expense");
            returnOnAssetsModel.assets_balance = chartingService.GetAccountTypeTotalBalance("Asset");
            returnOnEquityModel = new ReturnOnEquityModel();
            returnOnEquityModel.equity_balance = chartingService.GetAccountTypeTotalBalance("Equity");
            quickRatioModel = new QuickRatioModel();
            List<string> inventoryIdList = new List<string>();
            inventoryIdList.Add("115"); // Office Equipment
            inventoryIdList.Add("140"); // Merchandise Inventory

            quickRatioModel.inventory_balance = chartingService.GetAccountIdsTotalBalane(inventoryIdList);
            dashboardBundleModel = 
                new DashboardBundleModel(
                currentRaitoModel, 
                returnOnAssetsModel,
                returnOnEquityModel,
                quickRatioModel
                );
                
            int? pendingCount = _dbConnectorService.PendingJournalCount();
            if(pendingCount <= 0)
            {
                ViewBag.pendingJournalCount = 0;
            }
            else
            {
                ViewBag.pendingJournalCount = (int)pendingCount;
            }
            List<ChartMonth> IEMonths = GetChartData();
            dashboardBundleModel.IEMonths = IEMonths;
            LinkedList<Top5ExpenseModel> Top5Expense = Top5Expenses();
            dashboardBundleModel.Top5ListExpense = Top5Expense;
            LinkedList<Top5IncomeModel> Top5Revenue = Top5Revenues();
            dashboardBundleModel.Top5ListRevenue = Top5Revenue;
            return View(dashboardBundleModel);
        }
        // Helper method to get chart data Revenue and Expenses
        public List<ChartMonth> GetChartData()
        {
            SettingsModel systemSettings = new SettingsModel();
            systemSettings = _dbConnectorService.GetSystemSettings();
            DateTime lastClosingDate = (DateTime)systemSettings.open_close_date;
            ViewBag.lastClosingDate = lastClosingDate.ToString("yyyy-MM-dd");
            string fromDate = lastClosingDate.ToString("MM-dd-yyyy");
            int startingMonth = Int32.Parse(fromDate.Split("-")[0]);
            List<int?> months = new List<int?>();

            // Create a list of months starting from the startingMonth and wrapping around
            for (int i = 0; i < 12; i++)
            {
                int month = (startingMonth + i - 1) % 12 + 1;
                months.Add(month);
            }

            List<AccountsModel> allAccounts = _dbConnectorService.GetChartOfAccounts();
            List<ChartMonth> IEData = new List<ChartMonth>();

            // Get the total for each account type and month
            for (int i = 0; i < months.Count; i++)
            {
                string monthNumStr = months[i].ToString();
                if (monthNumStr.Length == 1)
                {
                    monthNumStr = "0" + monthNumStr;
                }
                ChartMonth nextMonth = new ChartMonth();
                nextMonth.month = Int32.Parse(monthNumStr);
                string[] monthAbbr = {
                    "Jan", "Feb", "Mar", "Apr", "May", "Jun",
                    "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"
                };
                nextMonth.monthName = monthAbbr[(int)months[i] - 1];
                foreach (var account in allAccounts)
                {
                    if (account.type == "Revenue" && account.current_balance != 0)
                    {
                        decimal amount = _dbConnectorService.GetAccountBalanceForMonthByMonth(account.number, monthNumStr);
                        nextMonth.revenueTotal = nextMonth.revenueTotal + (double)amount;
                    }
                    if (account.type == "Expense" && account.current_balance != 0)
                    {
                        decimal amount = _dbConnectorService.GetAccountBalanceForMonthByMonth(account.number, monthNumStr);
                        nextMonth.enpensesTotal = nextMonth.enpensesTotal + (double)amount;
                    }
                }
                IEData.Add(nextMonth);
            }
            return IEData;
        }

        // Helper method to get chart data top 5 expenses
        public LinkedList<Top5ExpenseModel> Top5Expenses()
        {
            SettingsModel systemSettings = new SettingsModel();
            systemSettings = _dbConnectorService.GetSystemSettings();
            DateTime lastClosingDate = (DateTime)systemSettings.open_close_date;
            ViewBag.lastClosingDate = lastClosingDate.ToString("yyyy-MM-dd");
            string fromDate = lastClosingDate.ToString("MM-dd-yyyy");
            int startingMonth = Int32.Parse(fromDate.Split("-")[0]);

            List<AccountsModel> allAccounts = _dbConnectorService.GetChartOfAccounts();
            LinkedList<Top5ExpenseModel> linkedList = new LinkedList<Top5ExpenseModel>();

            foreach (var account in allAccounts)
            {
                if (account.type == "Expense" && account.current_balance != 0)
                {
                    Top5ExpenseModel top5ExpenseModel = new Top5ExpenseModel();
                    top5ExpenseModel.accountNum = account.number;
                    top5ExpenseModel.accountDesc = account.name;
                    top5ExpenseModel.accountAmount = (double)account.current_balance;
                    linkedList.AddLast(top5ExpenseModel);

                }
            }
            //sort greatest to least
            List<Top5ExpenseModel> list = new List<Top5ExpenseModel>(linkedList);
            list.Sort((x, y) => y.accountAmount.CompareTo(x.accountAmount));
            linkedList = new LinkedList<Top5ExpenseModel>(list);
            return linkedList;
        }


        // Helper method to get chart data top 5 revenue(Income) Accounts
        public LinkedList<Top5IncomeModel> Top5Revenues()
        {
            SettingsModel systemSettings = new SettingsModel();
            systemSettings = _dbConnectorService.GetSystemSettings();
            DateTime lastClosingDate = (DateTime)systemSettings.open_close_date;
            ViewBag.lastClosingDate = lastClosingDate.ToString("yyyy-MM-dd");
            string fromDate = lastClosingDate.ToString("MM-dd-yyyy");
            int startingMonth = Int32.Parse(fromDate.Split("-")[0]);

            List<AccountsModel> allAccounts = _dbConnectorService.GetChartOfAccounts();
            LinkedList<Top5IncomeModel> linkedList = new LinkedList<Top5IncomeModel>();


Views/Accounting/Index.cshtml
@using Microsoft.AspNetCore.Identity
@using oa.Areas.Identity.Data
@using oa.Services
@using oa.Models
@inject UserManager<AppUser> UserManager

@{
    string? userid = UserManager.GetUserId(User);
    string? role = "";
    if (userid != null)
    {
        DbConnectorService dbServ = new DbConnectorService();
        AppUserModel user = dbServ.GetUserDetailsById(userid);
        role = user.UserRole;
    }
    int journalCount = 0;
    if (ViewBag.pendingJournalCount != null)
    {
        journalCount = ViewBag.pendingJournalCount;
    } 

    string journalCountStr = journalCount.ToString();
    string journalMessage = $"There are {journalCountStr} pending journal entries!";
    // Revenue and expense chart
    List<string> monthsList = new List<string>();
    List<string> expensesList = new List<string>();
    List<string> revenuesList = new List<string>();
    for (var i = 0; i < Model.IEMonths.Count; i++)
    {
        monthsList.Add(Model.IEMonths[i].monthName);
        expensesList.Add(Model.IEMonths[i].enpensesTotal.ToString());
        revenuesList.Add(Model.IEMonths[i].revenueTotal.ToString());
    }
    string[] monthsArray = monthsList.ToArray();
    string[] expenses = expensesList.ToArray();
    string[] revenues = revenuesList.ToArray();

    // Top 5 Expense Chart
    List<string> accountDescriptionsListExpense = new List<string>();
    List<string> accountAmountsListExpense = new List<string>();
    var node = Model.Top5ListExpense.First; // Start from the first node
    for (var i = 0; i < Model.Top5ListExpense.Count; i++)
    {
        if (node != null)
        {
            string desc = node.Value.accountNum.ToString() + " - " + node.Value.accountDesc;
            accountDescriptionsListExpense.Add(desc);
            accountAmountsListExpense.Add(node.Value.accountAmount.ToString());
            node = node.Next; // Move to the next node
        }
    }
    string[] expenseDescripts = accountDescriptionsListExpense.ToArray();
    string[] expenseAmnts = accountAmountsListExpense.ToArray();
    int numberOfExpAccounts = 5;
    if (expenseDescripts.Count() < 5)
    {
        numberOfExpAccounts = expenseDescripts.Count();
    }
    string[] firstFiveElementExpenseDesc = new string[numberOfExpAccounts];
    string[] firstFiveElementExpenseAmnt = new string[numberOfExpAccounts];

    Array.Copy(expenseDescripts, firstFiveElementExpenseDesc, numberOfExpAccounts);
    Array.Copy(expenseAmnts, firstFiveElementExpenseAmnt, numberOfExpAccounts);

    // Top 5 Revenue(Income) Chart
    List<string> accountDescriptionsListRevenue = new List<string>();
    List<string> accountAmountsListRevenue = new List<string>();
    var nodeRevenue = Model.Top5ListRevenue.First; // Start from the first node
    for (var i = 0; i < Model.Top5ListRevenue.Count; i++)
    {
        if (nodeRevenue != null)
        {
            string desc = nodeRevenue.Value.accountNum.ToString() + " - " + nodeRevenue.Value.accountDesc;
            accountDescriptionsListRevenue.Add(desc);
            accountAmountsListRevenue.Add(nodeRevenue.Value.accountAmount.ToString());
            nodeRevenue = nodeRevenue.Next; // Move to the next nodeRevenue
        }
    }
    string[] revenueDescripts = accountDescriptionsListRevenue.ToArray();
    string[] revenueAmnts = accountAmountsListRevenue.ToArray();
    int numberOfRevAccounts = 5;
    if (revenueDescripts.Count() < 5)
    {
        numberOfRevAccounts = revenueDescripts.Count();
    }
    string[] firstFiveElementRevenueDesc = new string[numberOfRevAccounts];
    string[] firstFiveElementRevenueAmnt = new string[numberOfRevAccounts];
    
    Array.Copy(revenueDescripts, firstFiveElementRevenueDesc, numberOfRevAccounts);
    Array.Copy(revenueAmnts, firstFiveElementRevenueAmnt, numberOfRevAccounts);
}

<h1 class="text-center margin-top-120">Accounting Home</h1>
<p class="text-center">Welcome @UserManager.GetUserName(User)!</p>
<p class="text-center">Your current role is: @role</p>
@{
    if (journalCount > 0)
    {
      <p class="text-center txt-warning">@journalMessage</p>
    }
}
<hr />
<partial name="_DashboardPartial" />
<hr />
<div class="chart-container">
    <div class="chart-col-2">
        <canvas id="BarChart-1" height="325" width="500"></canvas>
    </div>
    <div class="chart-col-3">
        <div class="donut-chart-container">
            <canvas id="DonutChart-2" height="325" width="500"></canvas>
        </div>
    </div>
    <div class="chart-col-3">
        <div class="donut-chart-container">
            <canvas id="DonutChart-1" height="325" width="500"></canvas>
        </div>
    </div>    
</div>
<hr />
<div class="outer-container">
    <div class="container-row">
        <div class="btn-container">
            <div class="btn-row">
                <a class="nav-link text-dark" asp-controller="Accounting" asp-action="AddJounalEntries" data - bs - toggle="tooltip" data - bs - placement="bottom" data - bs - title="Journal entry page"><img class="btn-img" src="~/img/journal.jpg" /></a>
            </div>
            <div class="btn-row">
                <span class="btn-label">Journal Entry</span>
            </div>
        </div>
        <div class="btn-container">
            <div class="btn-row">
                <a class="nav-link text-dark" asp-controller="Accounting" asp-action="ChartOfAccounts" data - bs - toggle="tooltip" data - bs - placement="bottom" data - bs - title="Chart of Accounts page"><img class="btn-img" width="150" src="~/img/chart_of_accounts.jpg" /></a>
            </div>
            <div class="btn-row">
                <span class="btn-label">Chart of Accounts</span>
            </div>
        </div>
    </div>
    <hr />
    <div class="container-row">
        <div class="btn-container">
            <div class="btn-row">
                <a class="nav-link text-dark" asp-controller="Accounting" asp-action="viewIncomeStatement" data - bs - toggle="tooltip" data - bs - placement="bottom" data - bs - title="View the Income Statement"><img class="btn-img" width="150" src="~/img/income_statement.jpg" /></a>
            </div>
            <div class="btn-row">
                <span class="btn-label">Income Statement</span>
            </div>
        </div>
        <div class="btn-container">
            <div class="btn-row">
                <a class="nav-link text-dark" asp-controller="Accounting" asp-action="viewBalanceSheet" data - bs - toggle="tooltip" data - bs - placement="bottom" data - bs - title="View the Balance Sheet"><img class="btn-img" width="150" src="~/img/balance_sheet.jpg" /></a>
            </div>
            <div class="btn-row">
                <span class="btn-label">Balance Sheet</span>
            </div>
        </div>
        <div class="btn-container">
            <div class="btn-row">
                <a class="nav-link text-dark" asp-controller="Accounting" asp-action="viewTrialBalance" data - bs - toggle="tooltip" data - bs - placement="bottom" data - bs - title="View the Trial balance"><img class="btn-img" width="150" src="~/img/trial_balance.jpg" /></a>
            </div>
            <div class="btn-row">
                <span class="btn-label">Trial Balance</span>
            </div>
        </div>
        <div class="btn-container">
            <div class="btn-row">
                <a class="nav-link text-dark" asp-controller="Accounting" asp-action="viewOwnersEquity" data - bs - toggle="tooltip" data - bs - placement="bottom" data - bs - title="View the equity"><img class="btn-img" width="150" src="~/img/equity.jpg" /></a>
            </div>
            <div class="btn-row">
                <span class="btn-label">Owners Equity</span>
            </div>
        </div>

    </div>
</div>
<script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
<script>
    const colors = [
        'rgba(25, 135, 84, 0.5)', // green, income
        'rgba(91, 25, 135, 0.5)', // purple, expenses
        'rgba(25, 109, 135, 0.5)', // blue
        'rgba(135, 86, 25, 0.5)', // brown
        'rgba(135, 25, 25, 0.5)' // red
    ];
    const ctx1 = document.getElementById('BarChart-1');
    new Chart(ctx1, {
        type: 'bar',
        data: {
            labels: @Html.Raw(Json.Serialize(monthsArray)),
            datasets: [{
                label: 'Income',
                data: @Html.Raw(Json.Serialize(revenues)),
                backgroundColor: colors[0],
                borderColor: 'rgba(25, 135, 84, 1)',
                borderWidth: 1
            },
            {
                label: 'Expenses',
                data: @Html.Raw(Json.Serialize(expenses)),
                backgroundColor: colors[1],
                borderColor: 'rgba(91, 25, 135, 1)',
                borderWidth: 1
            }]
        },
        options: {
            scales: {
                y: {
                    beginAtZero: true
                }
            },
            plugins: {
                title: {
                    display: true,
                    text: 'Revenue and Expenses',
                    font: {
                        size: 18,
                        weight: 'bold'
                    }
                }
            },
            responsive: false,
        }
    });
    const ctx2 = document.getElementById('DonutChart-1').getContext('2d');
    new Chart(ctx2, {
        type: 'doughnut',
        data: {
            labels: @Html.Raw(Json.Serialize(firstFiveElementExpenseDesc)),
            datasets: [{
                label: 'Expenses',
                data: @Html.Raw(Json.Serialize(firstFiveElementExpenseAmnt)),
                backgroundColor: colors,
                hoverOffset: 2,
                radius: 100
            }]
        },
        options: {
            layout:{
                padding:{
                    left: 25
                }
            },
            plugins: {
                title: {
                    display: true,
                    text: 'Top Expenses',
                    position: 'top',
                    align: 'start',
                    font: {
                        size: 18,
                        weight: 'bold'
                    },
                    padding: {
                        top: 30,
                        left: 50
                    }                    
                },
                legend: {
                    display: true,
                    position: 'right',
                    align: 'start',
                    labels: {
                        boxWidth: 10,
                        padding: 5
                                                    
                    },
                    padding:{
                        top: 10
                    }
                }
            },
            responsive: true
        }
    });
    const ctx3 = document.getElementById('DonutChart-2').getContext('2d');
    new Chart(ctx3, {
        type: 'doughnut',
        data: {
            labels: @Html.Raw(Json.Serialize(firstFiveElementRevenueDesc)),
            datasets: [{
                label: 'Income',
                data: @Html.Raw(Json.Serialize(firstFiveElementRevenueAmnt)),
                backgroundColor: colors,
                hoverOffset: 2,
                radius: 100
            }]
        },
        options: {
            layout: {
                padding: {
                    left: 25
                }
            },
            plugins: {
                title: {
                    display: true,
                    text: 'Top Revenues',
                    position: 'top',
                    align: 'start',
                    font: {
                        size: 18,
                        weight: 'bold'
                    },
                    padding: {
                        top: 30,
                        left: 50
                    }
                },
                legend: {
                    display: true,
                    position: 'right',
                    align: 'start',
                    labels: {
                        boxWidth: 10,
                        padding: 5
                    },
                    padding: {
                        top: 10
                    }
                }
            },
            responsive: true
        }
    });
</script>

Views/Accounting/viewAccountLogs.cshtml
@using oa.Models
@using oa.Services
@model IEnumerable<oa.Models.LogModel>
<div class="text-center margin-top-120">
</div>
<h1 class="text-center mb-4">Account Name: @ViewBag.AccountName</h1>
<h2 class="text-center mb-4">Event Log </h2>
<div class="search-row-secondary">
    <div class="search-colum-3">
        <input type="text" id="searchInput" class="form-control mb-3" style="max-width:200px;" placeholder="Search...">
        <img src="~/img/search.svg" class="mng-acct-search-img" />
    </div>
</div>
<div class="table-wrapper margin-top-20">
    <table class="table table-striped">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.ChangeDate)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.UserId)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ChangedFrom)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ChangedTo)
            </th>

        </tr>
    </thead>
    <tbody id="tableBody">
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.ChangeDate)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.UserId)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.ChangedFrom)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.ChangedTo)
                </td>
            </tr>
        }
    </tbody>
</table>
</div>
@* Search and Filter *@
<script>
    document.getElementById('searchInput').addEventListener('keyup', function () {
        let input = this.value.toLowerCase();
        let rows = document.getElementById('tableBody').getElementsByTagName('tr');

        for (let i = 0; i < rows.length; i++) {
            let rowData = rows[i].getElementsByTagName('td');
            let match = false;

            for (let j = 0; j < rowData.length; j++) {
                if (rowData[j].innerText.toLowerCase().indexOf(input) > -1) {
                    match = true;
                    break;
                }
            }

            if (match) {
                rows[i].style.display = '';
            } else {
                rows[i].style.display = 'none';
            }
        }
    });
</script>

Views/Accounting/viewIncomeStatement.cshtml
@model oa.Models.IncomeStatementBundle
@{
    ViewData["Title"] = "viewIncomeStatement";
    string? asOfDate = ViewBag.asOfDate;
    string lastClosingDate = ViewBag.lastClosingDate;
    int? RevenueCounter = 0;
    int? ExpenseCounter = 0;
}

<div class="text-center margin-top-120">
    <div data-print-marker="print-content">
        <h1 class="text-center mb-2"><span class="accent-color">@ViewBag.businessName</span></h1>
        <h2 class="text-center mb-2">Income Statement</h2>
        <h3 class="text-center mb-4">As of: <span class="accent-color">@ViewBag.titleDate </span></h3>
    </div>
</div>
<div class="date-container">
    <form class="row g-3" asp-controller="Accounting" asp-action="viewIncomeStatement" method="post">
        <div class="col-auto">
            <label for="date" class="mr-1 padding-top-3">As of Date:</label>
        </div>
        <div class="col-auto">
            <input type="date" class="form-control mr-1" id="fromDate" name="fromDate" value="@lastClosingDate" required>
        </div>
        <div class="col-auto">
            <input type="date" class="form-control mr-1" id="toDate" name="toDate" value="@asOfDate" required>
        </div>
        <div class="col-auto">
            <button type="submit" class="btn btn-outline-primary mb-2">Update Report</button>
        </div>
    </form>
    <div class="col-auto" style="padding-left: 5px;">
        <input type="button" class="btn btn-outline-primary mb-2" value="Print" onclick="printDiv('print-content')">
    </div>
</div>
<div data-print-marker="print-content">
    <div class="table-wrapper">
        <table class="table table-striped">
            <thead class="table-top-row">
                <tr style="background-color: #fcb14f15; padding-left: 20px;">
                    <th style="text-align:left; padding-left: 100px;  font-weight: bold;">
                        Account:
                    </th>
                    <th style="width:60%"></th>
                    <th style="text-align:right; font-weight: bold;">
                        <span style="padding: 30px;">Amount:</span><span style="padding-right:45px;"">Total:</span>
                    </th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td style="text-align:left; padding-left: 40px; font-weight:600; font-size:15px;">Revenues</td>
                    <td></td>
                    <td></td>
                </tr>
                @foreach (var item in Model.RevenueAccountsList)
                {
                    @if (item.type.Equals("Revenue"))
                    {
                        <tr>
                            <td style="text-align:left;padding-left: 80px;">
                                @Html.DisplayFor(modelItem => item.name)
                            </td>
                            <td></td>
                            <td style="text-align:right;padding-right: 120px;">
                                @FormatNegativeDouble(((double)item.current_balance))
                            </td>
                        </tr>
                        RevenueCounter++;
                    }
                    @if (RevenueCounter == Model.RevenueAccountsList.Count)
                    {
                        <tr>
                            <td style="text-align:left;padding-left: 40px; font-weight:600; font-size:15px; padding-top:10px;">Total Revenues:</td>
                            <td></td>
                            <td style="text-align:right;padding-right:40px"><div class="top-border"><br><span class="total-text">@FormatNegativeDouble(Model.RevenueAccountsTotal)</span></div></td>
                        </tr>
                    }
                }
                <tr>
                    <td style="text-align:left;padding-left: 40px; font-weight:600; font-size:15px;">Expenses</td>
                    <td></td>
                    <td></td>
                </tr>
                @foreach (var item in Model.ExpenseAccountsList)
                {
                    @if (item.type.Equals("Expense") && item.current_balance != 0)
                    {
                        <tr>
                            <td style="text-align:left;padding-left: 80px;">
                                @Html.DisplayFor(modelItem => item.name)
                            </td>
                            <td></td>
                            <td style="text-align:right;padding-right: 120px;">
                                @FormatNegativeDouble(((double)item.current_balance))
                            </td>
                        </tr>
                        ExpenseCounter++;
                    }
                    @if (ExpenseCounter == Model.ExpenseAccountsList.Count)
                    {
                        <tr>
                            <td style="text-align:left;padding-left: 40px; font-weight:600; font-size:15px; padding-top:10px;">Total Expenses:</td>
                            <td></td>
                            <td style="text-align:right;padding-right:40px"><div class="top-border"><span class="total-text">@FormatNegativeDouble(Model.ExxpenseAccountsTotal)</span></div></td>
                        </tr>
                    }
                }
                <tr>
                    <td style="text-align:left;padding-left: 40px; font-weight:600; font-size:15px;">Net Income (Loss) </td>
                    <td></td>
                    <td style="text-align:right;padding-right:40px"><div class="top-border"></div><span class="total-text">@FormatNegativeDouble(Model.Net)</span><div class="top-border"><br><div class="top-border"><br></div></td>
                </tr>
            </tbody>
        </table>
    </div>
</div>

@functions {
    public static string FormatNegativeDouble(double? value)
    {
        if (value.HasValue)
        {
            Console.WriteLine($"Formatting value: {value}");
            if (value < 0)
            {
                return $"({Math.Abs(value.Value).ToString("C")})";
            }
            return value.Value.ToString("C");
        }
        return string.Empty;
    }
}